name: Test TiUP Nightly Package on macOS

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 */3 * * *'  # Run every 3 hours
  workflow_dispatch:      # Allow manual triggering

jobs:
  test-tiup-nightly:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-13, macos-12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
          auto-start: false
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Test OS version
        run: |
          echo "OS version: $(sw_vers)"
          echo "default shell: $(dscl . -read /Users/$(whoami) UserShell | awk '{print $2}')"

      - name: Install TiUP
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh
          source ~/.bash_profile
          tiup update playground

      - name: Checkout TiUP Nightly
        run: |
          source ~/.bash_profile
          make run-checker
